appname: tesla-charge
plugins:
  "Auth::OAuth":
    prefix: /auth
    success_url: /
    error_url: /
    providers:
      Github:
        tokens:
          client_id: your_client_id
          client_secret: your_client_secret