#ifndef TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H
#define TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H

#define STEPPER_FULLSTEP 4

#define PIN_IN1 8
#define PIN_IN2 9
#define PIN_IN3 10
#define PIN_IN4 11

#define PIN_ACTIVATE    7
#define PIN_RESET       6
#define MAX_SPEED       4000.0
#define SET_SPEED       4000
#define ACCELERATION    100.0

#define POSITION_OPEN   3225
//#define POSITION_OPEN   200
#define POSITION_CLOSED 0

#define DOOR_ACTIVATE_DEBOUNCE_DELAY 255

#endif //TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H
