#ifndef TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H
#define TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H

#define STEPPER_FULLSTEP 4

#define PIN_IN1 8
#define PIN_IN2 9
#define PIN_IN3 10
#define PIN_IN4 11

#define POSITION_OPEN   2048
#define POSITION_CLOSED 0

#endif //TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H
