#ifndef TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H
#define TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H

#include <Arduino.h>
#include <AccelStepper.h>

#define STEPPER_FULLSTEP 4

#define RESET_PIN       5   // D1
#define ACTIVATE_PIN    4   // D2
#define STEPPER_IN1_PIN 2   // D4
#define STEPPER_IN2_PIN 12  // D6
#define STEPPER_IN3_PIN 13  // D7
#define STEPPER_IN4_PIN 14  // D5

#define MAX_SPEED       4000.0
#define SET_SPEED       4000
#define ACCELERATION    100.0

#define POSITION_CLOSED 0
#define POSITION_OPEN   3225

#define DOOR_ACTIVATE_DEBOUNCE_DELAY 255

#endif //TESLA_CHARGE_GARAGE_DOOR_PROTOTYPE_H
